### ISSUE TITLE
Predict Document Similarity

### ISSUE THREAD

**Issue by AnyaMit** [mlampros/fastTextR#3]
Hi @mlampros,

Is there a way to use FastTextR to predict the top N number of similar documents? I've gone through the algorithm and can compile the doc2sum with k means (per your example), but having trouble being able to get top 5 most related to a single document. 

Thanks for your help.

**Comment by mlampros** [comment]
@AnyaMit  hello, 

one approach to find the top-n most similar documents would be to use an approximate nearest neighbor search based on the fasttext output word vectors. A while back I ported the [nmslib](https://github.com/nmslib/nmslib) python library in R and I wrote a [blog post](http://mlampros.github.io/2018/02/27/the_nmslibR_package/) on how it can be used (actually not for text processing but nmslib is applicable in many fields). You need a [python installation](https://github.com/mlampros/nmslibR/blob/master/README.md) (preferably python 3) to use the nmslib package from within R.

Besides the one I mentioned there are many others such as [faiss](https://github.com/facebookresearch/faiss) and this [tutorial explains](https://code.fb.com/data-infrastructure/faiss-a-library-for-efficient-similarity-search/) how similarity search in combination with word vectors works (it makes a mention to nmslib too). I'm not aware of any R implementation of faiss (you can do a search on the web) but if you able to use the [reticulate package](https://github.com/rstudio/reticulate) then you can load the python package of faiss from within Rstudio.
There is also a [benchmark](https://erikbern.com/2018/02/15/new-benchmarks-for-approximate-nearest-neighbors.html) of approximate nearest neighbors on the web.

As I said this is one approach and I think it scales well in comparison to other algorithms. 
You can also give a try to [text2vec](https://cran.r-project.org/web/packages/text2vec/vignettes/text-vectorization.html), [spacy](https://spacy.io/usage/vectors-similarity), [spacyr ](http://spacyr.quanteda.io/) or [gensim](https://radimrehurek.com/gensim/similarities/docsim.html) too.
