### ISSUE TITLE
Args to pointers issue

### ISSUE THREAD

**Issue by ghost** [mlampros/fastTextR#4]
Error in .Call("fastTextR_convert_args_to_pointers", PACKAGE = "fastTextR",  : 
  "fastTextR_convert_args_to_pointers" not available for .Call() for package "fastTextR"

I compiled the package from the repo. But for some reason I get this error when I try to use the package. Any idea how to solve this?

**Comment by mlampros** [comment]
@kresh6560 I'm sorry for the late reply,

would you mind giving additional information. For instance, 

* details on how you attempt to install the package (using the devtools package or directly by downloading the .zip file)
* about your operating system (OS) 
* in case that you have the  windows OS, if you have [Rtools](https://cran.r-project.org/bin/windows/Rtools/) installed and you are able to compile packages with Rcpp code

You should know that the fastTextR package is tested on [Linux](https://github.com/mlampros/fastTextR/blob/master/.travis.yml), Macintosh and [Windows](https://github.com/mlampros/fastTextR/blob/master/appveyor.yml) and it works fine.

**Comment by ghost** [comment]
Hi @mlampros ,
I am using devtools to install the package from github. 
Windows 10 64x OS
I got prompt for installing Rtools and did so when i tried to compile the code.

I got two warning messages as below:
Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
Other than this the installation was successful.

Am I missing something very basic.? Will really appreciate your guidance here.

**Comment by mlampros** [comment]
@kresh6560 I'm not sure I can explain the warning messages (probably a search on the web might give results related to R packages) but there is a second way to install the package by downloading the .zip file as described in the [README.md](https://github.com/mlampros/fastTextR/blob/master/README.md#fasttextr) file and in [this issue](https://github.com/mlampros/fastTextR/issues/2#issuecomment-431031301) too.
Are you able to use the package regardless of the warning messages?

**Comment by ghost** [comment]
@mlampros I was not able to use the package before though the installation was successful. I tried it on my other PC and it worked fine there,though while compiling I got the same error message. As a workaround I copied the package folder from the new system to the old system and now It works fine. Probably issue with the compiler. Not sure. Works perfectly now.

**Comment by mlampros** [comment]
@kresh6560 nice to hear that.

**Comment by mlampros** [comment]
hi @kresh6560,

I uploaded the [updated version of the fastText package](https://github.com/mlampros/fastText). It can be installed only from Github as it wasn't finally accepted from CRAN due to the fact that there are already two other versions of the same algorithm.
There is also a [blog post](http://mlampros.github.io/2019/04/11/fastText_updated_version/) explaining the new functionality.
This repository will be archived. New issues can be opened only in the new repository. Thanks.
