### ISSUE TITLE
PRoblem

### ISSUE THREAD

**Issue by byminh** [mlampros/fastTextR#6]
Hi,

I want to install the Fasttext package from computer of my company. Due to the company's firewall, I have to manually install this way:

> setwd('C:/your_folder/fastTextR/')
> Rcpp::compileAttributes(verbose = TRUE)
> setwd('C:/your_folder/')
> system("R CMD build fastTextR")
> system("R CMD INSTALL fastTextR_1.0.2.tar.gz")

Even through I tried to install Rtools but it still does not work:

> ============================================================
> 
> Configuration CCC :
> 
>     Proxy :
>         HTTP  = pxy-http-srv:1234
>         HTTPS = pxy-http-srv:1234
> 
>     Serveur de paquets (le seul accessible via le proxy) :
>         https://mirror.ibcp.fr/pub/CRAN/
> 
>     Librairie locale de paquets : 
>         C:\Developpement\R_Packages\
> 
>     Fichiers de config pris en compte :
>         C:/PROGRA~1/R/R-35~1.0\Renviron.site
>         C:/PROGRA~1/R/R-35~1.0\Rprofile.site
> Error in library("colorout") : 
>   no package named 'colorout' is found
> Stopped execution
> In R CMD INSTALL

Could someone please tell me how can I solve this problem?

Thanks a lot for your information!

**Comment by mlampros** [comment]
@byminh I'm sorry for the late reply,

I can't promise that I will be able to help you solve this issue, but do you attempt to install the fastTextR package from the command line (cmd)  or from an R language IDE such as Rstudio (on WIndows operating system)?
